GET https://localhost:3000/api HTTP/1.1
###
POST https://localhost:3000/api/fruits HTTP/1.1
content-type: application/json
Authorization: Bearer

###
POST https://localhost:3000/api/fruits HTTP/1.1
content-type: application/json

{
  "id": "2",
  "name": "Apple"
}
###
DELETE https://localhost:3000/api/fruits/634533b506e3ee3b4a7d7eb3 HTTP/1.1
###
POST https://localhost:3000/api/users/signup HTTP/1.1
content-type: application/json

{
  "username": "mine",
  "password": "password1"
}
###
DELETE https://localhost:3000/api/users/634533b106e3ee3b4a7d7eb1 HTTP/1.1
###
POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
  "username": "mine",
  "password": "password1"
}
