GET https://localhost:3000/api/issue HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVidW50dSIsInVzZXJJZCI6IjYzNjdiYjc4MzU3NzMyZWEzMDk1Y2RlZCIsImlhdCI6MTY2NzgxNTMyNywiZXhwIjoxNjY3ODE4OTI3fQ.V8b2vYhvgLCJ-ylPB5DnGEfK5B53i_aYdn2VcgvZjIQ

###
POST https://localhost:3000/api/issue HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVidW50dSIsInVzZXJJZCI6IjYzNjdiYjc4MzU3NzMyZWEzMDk1Y2RlZCIsImlhdCI6MTY2Nzc0MzYwMSwiZXhwIjoxNjY3NzQ3MjAxfQ.0EwcRMPffatloybbvzBjz5pD1W2ODW6LuJ8MAH5Dzx8

{
  "id": "2",
  "name": "Systems down"
}

###
DELETE https://localhost:3000/api/issue/6345a43b22712bc6956ffbf1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVidW50dSIsInVzZXJJZCI6IjYzNjdiYjc4MzU3NzMyZWEzMDk1Y2RlZCIsImlhdCI6MTY2Nzc0MzYwMSwiZXhwIjoxNjY3NzQ3MjAxfQ.0EwcRMPffatloybbvzBjz5pD1W2ODW6LuJ8MAH5Dzx8

###
POST https://localhost:3000/api/users/signup HTTP/1.1
content-type: application/json

{
  "username": "latest",
  "password": "user"
}
###
DELETE https://localhost:3000/api/users/634533b106e3ee3b4a7d7eb1 HTTP/1.1
###
POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
  "username": "ubuntu",
  "password": "user"
}
###
POST https://localhost:3000/api/issue HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVidW50dSIsInVzZXJJZCI6IjYzNjdiYjc4MzU3NzMyZWEzMDk1Y2RlZCIsImlhdCI6MTY2Nzc0MzYwMSwiZXhwIjoxNjY3NzQ3MjAxfQ.0EwcRMPffatloybbvzBjz5pD1W2ODW6LuJ8MAH5Dzx8

{
  "id": "2",
  "name": "Systems Down"
}
###