GET https://localhost:3000/api/issue HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJ1c2VySWQiOiI2MzQ1YTFiYjIyNzEyYmM2OTU2ZmZiZWUiLCJpYXQiOjE2NjU1MDgzNjUsImV4cCI6MTY2NTUxMTk2NX0.JNPAknzkzgIos1XDtRbhiW533mc0NVEyQuTKUqGSwro

###
POST https://localhost:3000/api/issue HTTP/1.1
content-type: application/json

{
  "id": "2",
  "name": "Systems down"
}
###
DELETE https://localhost:3000/api/issue/6345a43b22712bc6956ffbf1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJ1c2VySWQiOiI2MzQ1YTFiYjIyNzEyYmM2OTU2ZmZiZWUiLCJpYXQiOjE2NjU1MDgzNjUsImV4cCI6MTY2NTUxMTk2NX0.JNPAknzkzgIos1XDtRbhiW533mc0NVEyQuTKUqGSwro

###
POST https://localhost:3000/api/users/signup HTTP/1.1
content-type: application/json

{
  "username": "test",
  "password": "user"
}
###
DELETE https://localhost:3000/api/users/634533b106e3ee3b4a7d7eb1 HTTP/1.1
###
POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
  "username": "test",
  "password": "user"
}
###
POST https://localhost:3000/api/issue HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJ1c2VySWQiOiI2MzQ1YTFiYjIyNzEyYmM2OTU2ZmZiZWUiLCJpYXQiOjE2NjU1MDgzNjUsImV4cCI6MTY2NTUxMTk2NX0.JNPAknzkzgIos1XDtRbhiW533mc0NVEyQuTKUqGSwro

{
  "id": "2",
  "name": "Systems Down"
}
###